
  
name: Quality check

on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17 # Good practice: Match dev and deployment version
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3 # golangci-lint
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

  test:
    name: Test
    runs-on: ubuntu-20.04
    env:
      TESTING_PARALLEL_ENABLED: true
      GO111MODULE: on
      GOFLAGS: -mod=readonly
      ENVIRONMENT: localdev
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17 # Good practice: Match dev and deployment version
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests in verbose mode
        run: go test -v ./...
